name: Pipeline
on: push
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run deno install
        run: deno install
      - name: Check linter
        run: deno lint
      - name: Check formatting
        run: deno fmt --check
