name: Pipeline
on: push
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Run bun install
        run: bun install
      - name: Run lint
        run: bun run lint
